### ISSUE TITLE
Describe possible use cases

### ISSUE THREAD

**Issue by gofort** [patrickhilker/tedee_hass_integration#45]
Hi everyone, I have this lock and have this integration installed. At the same time, I can't find any use cases for it, but as this integration exists, I believe use cases exist too. 
It would be nice to see some in the README if possible :)

**Comment by bzumik1** [comment]
I am using it to lock the door when everyone leaves. To unlock the door with NFC tag, to monitor the battery and remind me to charge the lock when it is below 20% etc. 🙂

**Comment by patrickhilker** [comment]
I use it to automatically unlock my door when I am coming home (far better than the build in function by using a motion sensor in front of my door and a few smart template sensors) or getting down the stairs and to automatically lock it behind me (with the help of a magnet contact). I also have Home Assistant send me notifications when someone is ringing or standing in front of my door with an action to unlock the door in it.

**Comment by bzumik1** [comment]
I really like this thread. It is nice to see all the possible use cases.

**Comment by bzumik1** [comment]
> I use it to automatically unlock my door when I am coming home (far better than the build in function by using a motion sensor in front of my door and a few smart template sensors) or getting down the stairs and to automatically lock it behind me (with the help of a magnet contact). I also have Home Assistant send me notifications when someone is ringing or standing in front of my door with an action to unlock the door in it.

Could you please describe in more details the unlock automation? What are the rules to unlock the door.

**Comment by patrickhilker** [comment]
> Could you please describe in more details the unlock automation? What are the rules to unlock the door.

I have a binary template sensor, that is true/on if I came home in the last 5 minutes (based on my mobile phone connecting to my wifi):

```
  - binary_sensor:
      - name: Patrick ist gerade nach Hause gekommen
        state: "True"
        auto_off: 00:05:00
    trigger:
      - platform: state
        entity_id:
          - person.patrick_hilker
        to: "home"
```

When this sensor and the motion sensor are on, the door unlocks.
